export default {
  "login": "wdahlia",
  "id": 108653518,
  "node_id": "U_kgDOBnnrzg",
  "avatar_url": "https://avatars.githubusercontent.com/u/108653518?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/wdahlia",
  "html_url": "https://github.com/wdahlia",
  "followers_url": "https://api.github.com/users/wdahlia/followers",
  "following_url": "https://api.github.com/users/wdahlia/following{/other_user}",
  "gists_url": "https://api.github.com/users/wdahlia/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/wdahlia/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/wdahlia/subscriptions",
  "organizations_url": "https://api.github.com/users/wdahlia/orgs",
  "repos_url": "https://api.github.com/users/wdahlia/repos",
  "events_url": "https://api.github.com/users/wdahlia/events{/privacy}",
  "received_events_url": "https://api.github.com/users/wdahlia/received_events",
  "type": "User",
  "site_admin": false,
  "name": "dahlia",
  "company": null,
  "blog": "wdahlia.oopy.io",
  "location": "Changnyeong-gun, South Korea",
  "email": null,
  "hireable": null,
  "bio": "👩🏻‍💻",
  "twitter_username": null,
  "public_repos": 33,
  "public_gists": 0,
  "followers": 47,
  "following": 53,
  "created_at": "2022-07-04T06:42:30Z",
  "updated_at": "2023-03-14T14:56:09Z"
}